spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

# 七牛的上传凭证秘钥
qiniu:
  accessKey: AaW1qJ3mIWKX22K7PV5fH-0K41gECx1GwHi3SE78
  secretKey: DsPufr8klqiQuk6tjYLANZvQ_c40iZIZu_EE9Sgr
  bucket: fatcao-home